### ISSUE TITLE
Add a warm white dubious liquid and other stuff:>

### ISSUE THREAD

**Issue by dennisjosh16** [TheSaus/DubiousWhiteLiquidustry#2]
That slows and burns the enemy. 

Rename the factory to White Dubious Liquid Ejector

Warm white dubious ejector- ejects warm white dubious liquid ( requires white dubious liquid and slag)

Solid White Dubious Ingot- a solidified substance that uses for new technology and ammunition.

Solid White Dubious Solidifier- heats the substance and produces solid white Dubious (requires WDL and titanium for hardening it) 

Dubious launcher- launches solid white dubious projectile that exploded into a liquid that slows enemies.

Dubious auto cannon- fires solid white dubious bullets that deals little damage. Good for pleasuring the daggers;)

White Dubious Mine- a trap that explodes into a white dubious liquid slowing enemy down.

Ejector- a unit that sprays white liquids at enemies

**Comment by TheSaus** [comment]
I won't personally be adding anything to the mod from here. if you really want something added feel free to pull request
